"""
Django settings for Nextremitly project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3+11v8dkjz1bs)^(d&@lvwcmp^xc@9(c03+aw=8($uto7)$9i^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  
    'http://localhost:3000',  # React dev server (si différent)
    'http://localhost:8080',  # Autres ports possibles
]

CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',


    'core',
    'user',


]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Rest Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # AJOUTS pour le système de paiement
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'payment_create': '100/minute',
        'payment_confirm': '50/minute',
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'm.yahyabettah@gmail.com'
EMAIL_HOST_PASSWORD = 'gfft susb qwof gzkc'

ROOT_URLCONF = 'Nextremitly.urls'
AUTH_USER_MODEL = 'user.CustUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Nextremitly.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 1OMpIsHpIDKdtqi9

# localy:
# DATABASES = {
#     'default': dj_database_url.parse(
#         'postgresql://postgres:1OMpIsHpIDKdtqi9@db.ipvtbiasrjrouzveevrt.supabase.co:5432/postgres',
#         ssl_require=True
#     )}

# heroku:
DATABASES = {
    'default': dj_database_url.parse(
        'postgresql://postgres.ipvtbiasrjrouzveevrt:1OMpIsHpIDKdtqi9@aws-1-eu-west-1.pooler.supabase.com:5432/postgres',
        ssl_require=True
    )
}




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     } 
# }

# CORS_ALLOW_ALL_ORIGINS = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Frontend URLs (ajoutez ces variables)
FRONTEND_URL = 'http://localhost:5173'  # Votre URL React
API_BASE_URL = 'http://localhost:8000'  # Votre URL Django

# Payment Gateway Configuration
PAYMENT_GATEWAY = {
    'TRANSACTION_FEE_PERCENTAGE': 2.0,  # 2% fee
    'MINIMUM_AMOUNT': 10.0,  # Minimum transaction amount
    'MAXIMUM_AMOUNT': 1000000.0,  # Maximum transaction amount
    'SESSION_TIMEOUT_MINUTES': 30,  # Payment session timeout
    'OTP_EXPIRY_MINUTES': 5,  # OTP expiry time
    'DEFAULT_CURRENCY': 'MRU',  # Mauritanian Ouguiya
    'SUPPORTED_CURRENCIES': ['MRU', 'USD', 'EUR'],
    'WEBHOOK_RETRY_ATTEMPTS': 3,
    'WEBHOOK_RETRY_DELAY_SECONDS': 60,
}


# Bank API Configuration (simulées pour le développement)
BANK_APIS = {
    'bankily': {
        'base_url': 'https://api.bankily.mr/v1',
        'api_key': 'test_bankily_key',
        'api_secret': 'test_bankily_secret',
        'timeout': 30,
    },
    'sedad': {
        'base_url': 'https://api.sedad.mr/v1',
        'api_key': 'test_sedad_key',
        'api_secret': 'test_sedad_secret',
        'timeout': 30,
    },
    'bimbank': {
        'base_url': 'https://api.bimbank.mr/v2',
        'api_key': 'test_bimbank_key',
        'api_secret': 'test_bimbank_secret',
        'timeout': 30,
    },
    'paypal': {
        'base_url': 'https://api.sandbox.paypal.com',
        'client_id': 'your-paypal-client-id',
        'client_secret': 'your-paypal-client-secret',
        'timeout': 30,
    },
    'stripe': {
        'base_url': 'https://api.stripe.com/v1',
        'api_key': 'sk_test_your_stripe_secret_key',
        'timeout': 30,
    },
    'mtn_mobile_money': {
        'base_url': 'https://api.mtn.mr/mobilemoney/v1',
        'api_key': 'test_mtn_key',
        'api_secret': 'test_mtn_secret',
        'timeout': 30,
    }
}

# ! no need i think just in case
# Cache Configuration (optionnel - pour Redis si vous l'installez plus tard)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#     }
# }

# Celery Configuration (optionnel - pour plus tard)
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'UTC'


# Logging Configuration
import os
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'nextremitly.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'payment_gateway': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Créer le dossier logs s'il n'existe pas
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

CHINGUISOFT_VALIDATION_KEY = 'bW1FiqD0fvQ2B3jQ'
CHINGUISOFT_TOKEN = 'zYzGxXdBuEKlJscJgaSud7wvQWUKUQaB'