# Generated by Django 4.2.7 on 2025-12-18 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nom_complet', models.CharField(default='', max_length=100)),
                ('adrese', models.CharField(default='', max_length=255)),
                ('numero_telephone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('user_type', models.CharField(choices=[('buyer', 'Buyer'), ('merchant', 'Merchant')], default='buyer', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='MerchantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(help_text="Merchant's wallet ID/phone number with this provider", max_length=100)),
                ('wallet_name', models.CharField(help_text='Custom name for this wallet', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Merchant Wallet',
                'verbose_name_plural': 'Merchant Wallets',
            },
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MRU', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('success_url', models.URLField(help_text='URL to redirect after successful payment')),
                ('cancel_url', models.URLField(help_text='URL to redirect after cancelled payment')),
                ('webhook_url', models.URLField(blank=True, help_text='URL to receive payment status updates')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authenticated', 'User Authenticated'), ('wallet_selected', 'Wallet Selected'), ('otp_sent', 'OTP Sent'), ('processing', 'Processing Payment'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('customer_wallet_phone', models.CharField(blank=True, help_text="Customer's wallet phone number", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data from ecommerce')),
                ('authenticated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('selected_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.merchantwallet')),
            ],
            options={
                'verbose_name': 'Payment Session',
                'verbose_name_plural': 'Payment Sessions',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.CharField(default=user.models.generate_qr_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the QR code', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('qr_type', models.CharField(choices=[('static', 'Static Amount'), ('dynamic', 'Dynamic Amount')], default='static', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('scans_count', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for static QR codes', max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
            },
        ),
        migrations.CreateModel(
            name='WalletProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bankily', 'Bankily'), ('sedad', 'Sedad'), ('bimbank', 'Bimbank'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('mtn_mobile_money', 'MTN Mobile Money')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Provider logo or icon image', null=True, upload_to='wallet_providers/')),
                ('is_active', models.BooleanField(default=True)),
                ('api_endpoint', models.URLField(help_text="Bank's API endpoint for transactions")),
                ('supports_otp', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wallet Provider',
                'verbose_name_plural': 'Wallet Providers',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('custuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
            },
            bases=('user.custuser',),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('custuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('verification_status', models.BooleanField(default=False)),
                ('activation_status', models.BooleanField(default=True)),
                ('bank_account_number', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
            },
            bases=('user.custuser',),
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField()),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='user.paymentsession')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
            },
        ),
        migrations.CreateModel(
            name='QRPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MRU', max_length=3)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_wallet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='user.qrcode')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_payment_sessions', to='user.merchant')),
            ],
            options={
                'verbose_name': 'QR Payment Session',
                'verbose_name_plural': 'QR Payment Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRPaymentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='user.qrpaymentsession')),
            ],
            options={
                'verbose_name': 'QR Payment OTP',
                'verbose_name_plural': 'QR Payment OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('transaction', 'Transaction Verification'), ('login', 'Login Verification')], default='verification', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='user.paymentsession')),
            ],
            options={
                'verbose_name': 'Payment OTP',
                'verbose_name_plural': 'Payment OTPs',
            },
        ),
        migrations.CreateModel(
            name='OTP_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('transaction', 'Transaction Verification'), ('login', 'Login Verification')], default='verification', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User OTP',
                'verbose_name_plural': 'User OTPs',
            },
        ),
        migrations.AddField(
            model_name='merchantwallet',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.walletprovider'),
        ),
        migrations.CreateModel(
            name='WalletVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('transaction', 'Transaction Verification'), ('login', 'Login Verification')], default='verification', max_length=50)),
                ('wallet_id', models.CharField(help_text='Wallet ID/phone number being verified', max_length=100)),
                ('wallet_name', models.CharField(help_text='Custom name for this wallet', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='pending', max_length=20)),
                ('wallet_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.walletprovider')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_otps', to='user.merchant')),
            ],
            options={
                'verbose_name': 'Wallet Verification OTP',
                'verbose_name_plural': 'Wallet Verification OTPs',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('transfer', 'Transfer')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MRU', max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender_wallet_phone', models.CharField(max_length=20)),
                ('external_transaction_id', models.CharField(blank=True, help_text='Transaction ID from bank/provider', max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user.paymentsession')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('receiver_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.merchantwallet')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender_wallet_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_transactions', to='user.walletprovider')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user.merchant')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qrcode',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='user.merchant'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='user.merchant'),
        ),
        migrations.AddField(
            model_name='merchantwallet',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='user.merchant'),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=100)),
                ('key_prefix', models.CharField(editable=False, max_length=10)),
                ('key_hash', models.CharField(editable=False, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_test_mode', models.BooleanField(default=True, help_text='Whether this key is for testing')),
                ('can_create_sessions', models.BooleanField(default=True)),
                ('can_view_transactions', models.BooleanField(default=True)),
                ('can_refund', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='user.merchant')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['status'], name='qr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['created_at'], name='qr_created_at_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merchantwallet',
            unique_together={('merchant', 'provider', 'wallet_id')},
        ),
    ]
