# Generated by Django 4.2.7 on 2025-06-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(help_text="Merchant's wallet ID/phone number with this provider", max_length=100)),
                ('wallet_name', models.CharField(help_text='Custom name for this wallet', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='user.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Wallet',
                'verbose_name_plural': 'Merchant Wallets',
            },
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MRU', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('success_url', models.URLField(help_text='URL to redirect after successful payment')),
                ('cancel_url', models.URLField(help_text='URL to redirect after cancelled payment')),
                ('webhook_url', models.URLField(blank=True, help_text='URL to receive payment status updates')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authenticated', 'User Authenticated'), ('wallet_selected', 'Wallet Selected'), ('otp_sent', 'OTP Sent'), ('processing', 'Processing Payment'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('customer_wallet_phone', models.CharField(blank=True, help_text="Customer's wallet phone number", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data from ecommerce')),
                ('authenticated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='user.merchant')),
                ('selected_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.merchantwallet')),
            ],
            options={
                'verbose_name': 'Payment Session',
                'verbose_name_plural': 'Payment Sessions',
            },
        ),
        migrations.CreateModel(
            name='WalletProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bankily', 'Bankily'), ('sedad', 'Sedad'), ('bimbank', 'Bimbank'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('mtn_mobile_money', 'MTN Mobile Money')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_endpoint', models.URLField(help_text="Bank's API endpoint for transactions")),
                ('supports_otp', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wallet Provider',
                'verbose_name_plural': 'Wallet Providers',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField()),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='user.paymentsession')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('transfer', 'Transfer')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MRU', max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender_wallet_phone', models.CharField(max_length=20)),
                ('external_transaction_id', models.CharField(blank=True, help_text='Transaction ID from bank/provider', max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user.merchant')),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user.paymentsession')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('receiver_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.merchantwallet')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender_wallet_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_transactions', to='user.walletprovider')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('transaction', 'Transaction Verification'), ('login', 'Login Verification')], default='verification', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='user.paymentsession')),
            ],
            options={
                'verbose_name': 'Payment OTP',
                'verbose_name_plural': 'Payment OTPs',
            },
        ),
        migrations.AddField(
            model_name='merchantwallet',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.walletprovider'),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=100)),
                ('key_prefix', models.CharField(editable=False, max_length=10)),
                ('key_hash', models.CharField(editable=False, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_test_mode', models.BooleanField(default=True, help_text='Whether this key is for testing')),
                ('can_create_sessions', models.BooleanField(default=True)),
                ('can_view_transactions', models.BooleanField(default=True)),
                ('can_refund', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='user.merchant')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.AlterUniqueTogether(
            name='merchantwallet',
            unique_together={('merchant', 'provider', 'wallet_id')},
        ),
    ]
