# Generated by Django 4.2.7 on 2025-06-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merchantwallet_paymentsession_walletprovider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('transaction', 'Transaction Verification'), ('login', 'Login Verification')], default='verification', max_length=50)),
                ('wallet_id', models.CharField(help_text='Wallet ID/phone number being verified', max_length=100)),
                ('wallet_name', models.CharField(help_text='Custom name for this wallet', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='pending', max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_otps', to='user.merchant')),
                ('wallet_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.walletprovider')),
            ],
            options={
                'verbose_name': 'Wallet Verification OTP',
                'verbose_name_plural': 'Wallet Verification OTPs',
            },
        ),
    ]
