# Generated by Django 4.2.7 on 2025-07-01 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_walletverificationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Titre du lien de paiement', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du produit/service')),
                ('link_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('variable_amount', 'Variable Amount'), ('subscription', 'Subscription')], default='variable_amount', max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe (si link_type = fixed_amount)', max_digits=12, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum autorisé', max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum autorisé', max_digits=12, null=True)),
                ('currency', models.CharField(default='MRU', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('one_time_used', 'One Time Used')], default='active', max_length=20)),
                ('is_one_time_use', models.BooleanField(default=False, help_text='Lien à usage unique')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration du lien", null=True)),
                ('success_redirect_url', models.URLField(blank=True, help_text='URL de redirection après paiement réussi')),
                ('cancel_redirect_url', models.URLField(blank=True, help_text='URL de redirection après annulation')),
                ('send_email_notifications', models.BooleanField(default=True)),
                ('send_sms_notifications', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, help_text='Email pour notifications (optionnel)', max_length=254)),
                ('notification_phone', models.CharField(blank=True, help_text='Téléphone pour SMS (optionnel)', max_length=20)),
                ('total_payments', models.IntegerField(default=0)),
                ('total_amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='user.merchant')),
            ],
            options={
                'verbose_name': 'Payment Link',
                'verbose_name_plural': 'Payment Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('link_viewed', 'Lien consulté'), ('amount_entered', 'Montant saisi'), ('wallet_selected', 'Portefeuille sélectionné'), ('payment_completed', 'Paiement terminé'), ('payment_failed', 'Paiement échoué'), ('payment_cancelled', 'Paiement annulé')], max_length=50)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='user.paymentlink')),
            ],
            options={
                'verbose_name': 'Payment Link Analytics',
                'verbose_name_plural': 'Payment Link Analytics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MRU', max_length=3)),
                ('customer_phone', models.CharField(help_text='Numéro de téléphone du client', max_length=20)),
                ('customer_email', models.EmailField(blank=True, help_text='Email du client (optionnel)', max_length=254)),
                ('customer_name', models.CharField(blank=True, help_text='Nom du client (optionnel)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('amount_entered', 'Montant saisi'), ('wallet_selected', 'Portefeuille sélectionné'), ('otp_sent', 'OTP envoyé'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('customer_location', models.CharField(blank=True, help_text='Localisation du client', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('merchant_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.merchantwallet')),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='user.paymentlink')),
                ('selected_wallet_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.walletprovider')),
            ],
            options={
                'verbose_name': 'Direct Payment Session',
                'verbose_name_plural': 'Direct Payment Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectPaymentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='user.directpaymentsession')),
            ],
            options={
                'verbose_name': 'Direct Payment OTP',
                'verbose_name_plural': 'Direct Payment OTPs',
            },
        ),
    ]
