# Generated by Django 4.2.7 on 2025-07-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_paymentlink_paymentlinkanalytics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlink',
            name='fixed_amount',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='is_one_time_use',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='min_amount',
        ),
        migrations.AddField(
            model_name='directpaymentotp',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Montant du paiement', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='directpaymentotp',
            name='currency',
            field=models.CharField(default='MRU', help_text='Devise du paiement', max_length=3),
        ),
        migrations.AddField(
            model_name='directpaymentotp',
            name='merchant_wallet',
            field=models.ForeignKey(blank=True, help_text='Portefeuille du commerçant', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.merchantwallet'),
        ),
        migrations.AddField(
            model_name='directpaymentotp',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Provider du portefeuille sélectionné', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.walletprovider'),
        ),
        migrations.AddField(
            model_name='directpaymentotp',
            name='purpose',
            field=models.CharField(choices=[('verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('transaction', 'Transaction Verification'), ('login', 'Login Verification')], default='verification', max_length=50),
        ),
        migrations.AddField(
            model_name='directpaymentotp',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('failed', 'Échoué'), ('expired', 'Expiré')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='directpaymentotp',
            name='phone_number',
            field=models.CharField(help_text='Numéro du client', max_length=20),
        ),
        migrations.AlterField(
            model_name='directpaymentsession',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='cancel_redirect_url',
            field=models.URLField(blank=True, help_text='URL de redirection après annulation (optionnel)'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='description',
            field=models.TextField(blank=True, help_text='Description du produit/service (optionnel)'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration du lien (optionnel)", null=True),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='success_redirect_url',
            field=models.URLField(blank=True, help_text='URL de redirection après paiement réussi (optionnel)'),
        ),
    ]
