# Generated by Django 4.2.7 on 2025-07-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_paymentlink_fixed_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('qr_type', models.CharField(choices=[('static', 'Statique'), ('dynamic', 'Dynamique')], default='static', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('expired', 'Expiré')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scans_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='user.merchant')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'db_table': 'nextremitly_qrcodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRPaymentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('verification', 'Account Verification'), ('password_reset', 'Password Reset'), ('transaction', 'Transaction Verification'), ('login', 'Login Verification')], default='verification', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'QR Payment OTP',
                'verbose_name_plural': 'QR Payment OTPs',
            },
        ),
        migrations.CreateModel(
            name='QRPaymentSession',
            fields=[
                ('paymentsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.paymentsession')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='user.qrcode')),
            ],
            options={
                'verbose_name': 'QR Payment Session',
                'verbose_name_plural': 'QR Payment Sessions',
            },
            bases=('user.paymentsession',),
        ),
        migrations.RemoveField(
            model_name='directpaymentsession',
            name='merchant_wallet',
        ),
        migrations.RemoveField(
            model_name='directpaymentsession',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='directpaymentsession',
            name='selected_wallet_provider',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='paymentlinkanalytics',
            name='payment_link',
        ),
        migrations.DeleteModel(
            name='DirectPaymentOTP',
        ),
        migrations.DeleteModel(
            name='DirectPaymentSession',
        ),
        migrations.DeleteModel(
            name='PaymentLink',
        ),
        migrations.DeleteModel(
            name='PaymentLinkAnalytics',
        ),
        migrations.AddField(
            model_name='qrpaymentotp',
            name='qr_payment_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_otps', to='user.qrpaymentsession'),
        ),
        migrations.AddField(
            model_name='qrpaymentotp',
            name='wallet_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.walletprovider'),
        ),
    ]
