# Generated by Django 4.2.7 on 2025-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_qrcode_qrpaymentotp_qrpaymentsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_type',
            field=models.CharField(choices=[('static', 'Statique'), ('dynamic', 'Dynamique')], max_length=20),
        ),
    ]
