# Generated by Django 4.2.7 on 2025-07-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_qrcode_qr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe pour les QR codes statiques', max_digits=12, null=True),
        ),
    ]
