# Generated by Django 4.2.7 on 2025-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_qrcode_fixed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
